# Generated by Django 3.2.6 on 2021-09-06 12:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest_admin', '0002_expenses_permonthexpenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='permonthexpenses',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
